[2022-11-02 15:10:46,230] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl manual__2022-11-02T15:09:45.473174+00:00 [queued]>
[2022-11-02 15:10:46,287] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl manual__2022-11-02T15:09:45.473174+00:00 [queued]>
[2022-11-02 15:10:46,291] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 15:10:46,292] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-11-02 15:10:46,297] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 15:10:46,374] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_xetra_etl> on 2022-11-02 15:09:45.473174+00:00
[2022-11-02 15:10:46,394] {standard_task_runner.py:52} INFO - Started process 1166 to run task
[2022-11-02 15:10:46,424] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xetra_DAG', 'run_xetra_etl', 'manual__2022-11-02T15:09:45.473174+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/xetra_DAG.py', '--cfg-path', '/tmp/tmponi_wore', '--error-file', '/tmp/tmp24umsz9c']
[2022-11-02 15:10:46,427] {standard_task_runner.py:80} INFO - Job 141: Subtask run_xetra_etl
[2022-11-02 15:10:48,433] {task_command.py:369} INFO - Running <TaskInstance: xetra_DAG.run_xetra_etl manual__2022-11-02T15:09:45.473174+00:00 [running]> on host 0163e0790208
[2022-11-02 15:10:48,733] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xetra_DAG
AIRFLOW_CTX_TASK_ID=run_xetra_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T15:09:45.473174+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-02T15:09:45.473174+00:00
[2022-11-02 15:10:48,748] {logging_mixin.py:115} INFO - meta_file.csv
[2022-11-02 15:11:14,458] {python.py:173} INFO - Done. Returned value was: None
[2022-11-02 15:11:14,493] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=xetra_DAG, task_id=run_xetra_etl, execution_date=20221102T150945, start_date=20221102T151046, end_date=20221102T151114
[2022-11-02 15:11:14,848] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-02 15:11:14,861] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1166. PIDs of all processes in the group: [1166]
[2022-11-02 15:11:14,864] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1166
[2022-11-02 15:11:14,867] {process_utils.py:75} INFO - Process psutil.Process(pid=1166, status='terminated', exitcode=0, started='15:10:46') (1166) terminated with exit code 0
