[2022-12-11 19:20:17,870] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-24T15:00:00+00:00 [queued]>
[2022-12-11 19:20:17,912] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-24T15:00:00+00:00 [queued]>
[2022-12-11 19:20:17,917] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 19:20:17,919] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-11 19:20:17,935] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 19:20:18,126] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_etl_process> on 2022-11-24 15:00:00+00:00
[2022-12-11 19:20:18,176] {standard_task_runner.py:52} INFO - Started process 267 to run task
[2022-12-11 19:20:18,262] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_DAG', 'run_etl_process', 'scheduled__2022-11-24T15:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/etl_DAG.py', '--cfg-path', '/tmp/tmp1g9nz8il', '--error-file', '/tmp/tmp1sn33w82']
[2022-12-11 19:20:18,268] {standard_task_runner.py:80} INFO - Job 207: Subtask run_etl_process
[2022-12-11 19:20:19,184] {task_command.py:369} INFO - Running <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-24T15:00:00+00:00 [running]> on host 0163e0790208
[2022-12-11 19:20:20,555] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_DAG
AIRFLOW_CTX_TASK_ID=run_etl_process
AIRFLOW_CTX_EXECUTION_DATE=2022-11-24T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-24T15:00:00+00:00
[2022-12-11 19:21:19,314] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 19:21:20,678] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_DAG, task_id=run_etl_process, execution_date=20221124T150000, start_date=20221211T192017, end_date=20221211T192120
[2022-12-11 19:21:22,676] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-11 19:21:22,985] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 267. PIDs of all processes in the group: [267]
[2022-12-11 19:21:23,085] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 267
[2022-12-11 19:21:23,095] {process_utils.py:75} INFO - Process psutil.Process(pid=267, status='terminated', exitcode=0, started='19:20:18') (267) terminated with exit code 0
